# luci-theme-ssn
#		Copyright 2017 Julien Schmidt <js@stusta.net>
# luci-theme-darkmatter
# 		Copyright 2017 chrono <https://apollo.open-resource.org>
# luci-theme-material
# 		Copyright 2015 Lutty Yang <lutty@wcan.in>
# luci-theme-bootstrap:
# 		Copyright 2008 Steven Barth <steven@midlink.org>
# 		Copyright 2008 Jo-Philipp Wich <jow@openwrt.org>
# 		Copyright 2012 David Menting <david@nut-bolt.nl>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=SSN Theme
LUCI_DEPENDS:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
